// [Number of decimal points, suffix, friendly name, better direction]
// 1 = higher is better, 0 = neutral, -1 = lower is better
export const mw2StatFormat = {
    rateOfFire : [0, "rpm", "Fire Rate", 1],
    preFireDelay : [2, "ms", "Pre-Fire Delay", -1],
    muzzleVelocity : [0, "m/s", "Muzzle Velocity", 1],
    displayBurstDelay : [0, "ms", "Burst Delay", -1],
    pelletCount : [0,"", "Pellet Count", 1],
    magazineSize : [0, "", "Ammo Count", 1],
    reloadTime : [2, "s", "Reload Time", -1],
    reloadAddTime : [2, "s", "Reload Add Time", -1],
    reloadEmptyTime : [2, "s", "Empty Reload Time", -1],
    reloadEmptyAddTime : [2, "s", "Empty Reload Add Time", -1],
    rechamberTime : [0, "ms", "Rechamber Time", -1],
    movementSpeedTacticalSprint : [2, "m/s", "Tactical Sprint", 1],
    movementSpeedSprint : [2, "m/s", "Sprint", 1],
    movementSpeedHipForward : [2, "m/s", "Forward", 1],
    movementSpeedHipBackpedal : [2, "m/s", "Backpedal", 1],
    movementSpeedHipStrafe : [2, "m/s", "Strafe", 1],
    aimDownSightTime : [0, "ms", "ADS Time", -1],
    aimOutTime : [0, "ms", "Time To Exit ADS", -1],
    fov : [0, "°", "Field of View (FoV)", 0],
    dropTime : [0, "ms", "Drop Time", -1],
    raiseTime : [0, "ms", "Raise Time", -1],
    sprintToFire : [0, "ms", "Sprint to Fire", -1],
    tacSprintToFire : [0, "ms", "Tactical Sprint to Fire", -1],
    meleeDamage : [0, "", "Melee Damage", 1],
    meleeHitsToKill : [0, "", "Melee Hits to Kill", -1],
    meleeLungeDistanceInches : [1, '″', "Melee Lunge Distance", 1],
    tacSprintDuration : [2, "s", "Sprint Duration", 1],
    movementSpeedADSForward : [2, "m/s", "ADS Forward", 1],
    movementSpeedADSBackpedal : [2, "m/s", "ADS Backpedal", 1],
    movementSpeedADSStrafe : [2, "m/s", "ADS Strafe", 1],
    viewKickPitchMultiplier : [2, "x", "View Kick Ver Mul", -1],
    viewKickYawMultiplier : [2, "x", "View Kick Hor Mul", -1],
    gunKickPitchMultiplier : [2, "x", "Gun Kick Ver Mul", -1],
    gunKickYawMultiplier : [2, "x", "Gun Kick Hor Mul", -1],
    crouchGunKickMultiplier : [2, "x", "Crouch Gun Kick Mul", -1],
    proneGunKickMultiplier : [2, "x", "Prone Gun Kick Mul", -1],
    crouchViewKickMultiplier : [2, "x", "Crouch View Kick Mul", -1],
    proneViewKickMultiplier : [2, "x", "Prone View Kick Mul", -1],
    initialRecoilEndCount : [0, "", "Ends After Shot #", 0],
    initialGunKickMultiplier : [2, "x", "Initial Gun Kick Mul", -1],
    initialViewKickMultiplier : [2, "x", "Initial View Kick Mul", -1],
    sustainedRecoilStartCount : [0, "", "Begins On Shot #", 0],
    sustainedGunKickMultiplier : [2, "x", "Sustained Gun Kick Mul", -1],
    sustainedViewKickMultiplier : [2, "x", "Sustained View Kick Mul", -1],
    adsSpread : [4, "°", "ADS Spread", -1],
    hipfireStandMin : [4, "°", "Min Hipfire Spread", -1],
    hipfireStandMoveMax : [4, "°", "Moving Hipfire Spread", -1],
    hipfireStandMax : [4, "°", "Max Hipfire Spread", -1],
    damageRangeMultiplier : [2, "x", "Damage Range Mul", 1],
    viewCenterSpeed : [0, "", "View Centerspeed", 1],
    gunCenterSpeed : [0, "", "Gun Centerspeed", 1],
    idleSwayWidth: [2, "°", "Idle Sway Width", -1],
    idleSwayHeight: [2, "°", "Idle Sway Height", -1],
    gunBobWidth: [2, "°", "Gun Bob Width", -1],
    gunBobHeight: [2, "°", "Gun Bob Height", -1]
};